### ISSUE TITLE
TRACE method with NSS returns 404 status

### ISSUE THREAD

**Issue by bourgeoa** [solid/specification-tests#114]
https://github.com/solid-contrib/specification-tests/blob/6fe781855cdf0104909123ee0c28624f4bed4fd6/protocol/read-write-resource/method-not-allowed.feature#L12

https://github.com/solid-contrib/specification-tests/blob/6fe781855cdf0104909123ee0c28624f4bed4fd6/protocol/read-write-resource/method-not-allowed.feature#L7

**Comment by edwardsph** [comment]
Does NSS support the TRACE method - if not, it MUST respond with 405: https://solidproject.org/TR/protocol#reading-writing-resources. There was an argument that the 400, 501 responses are also valid but no-one has suggested 404 is correct as that is related to the resource at this URL not being found which is not true
