### ISSUE TITLE
How to include a specification test in the repo?

### ISSUE THREAD

**Issue by brownhoward** [solid/specification-tests#23]
For a test to be included in the specification test repo, I am assuming:
1. It must be PRed as an “unreviewed” test.
2. Reviewed by appropriate personnel to confirm that it conforms to the Solid specification.
3. If appropriate, updated the test to be marked as “reviewed”

So some questions:
1. What is the process for reviewing the tests?
2. Who needs to review the test?
3. Is there a way of automatically setting newly PRed tests as “unreviewed”?

**Comment by edwardsph** [comment]
A proposed process has been defined here: https://github.com/solid/specification-tests/blob/main/CONTRIBUTING.md

It needs to evolve as we start to use it but further suggestions can be made as PRs on that file.
